kind: Secret
apiVersion: v1
metadata:
  name: {{ include "clickup-report.fullname" . }}-secret
data:
  session: {{ .Values.secret.session | b64enc | quote }}
  clientSecret: {{ .Values.secret.oauth.clientSecret | b64enc | quote }}
  clientID: {{ .Values.secret.oauth.clientID | b64enc | quote }}
